### ISSUE TITLE
Quicker edit access

### ISSUE THREAD

**Issue by wbrowar** [nystudio107/craft-imageoptimize#15]
If it's possible, adding a click event to the "Focal Point set" text, or adding an "Edit Image with Craft" button that would open up Craft's image editor would be a nice convenience for clients.

I realize this only saves about 2 clicks, but if you're quickly processing a bunch of images, it would be a bit of a time saver.

**Comment by davidhellmann** [comment]
Yes,  the focal point Implantation in C3 is a bit pain. Is not possible to add a focal point within an entry direct. 

+1

**Comment by khalwat** [comment]
I like the idea; I'm just not sure how to do it.

**Comment by khalwat** [comment]
The P&T folks solved this one by adding an "Edit" button on the image previews.
